repo:
  - '*'

github-ations:
  - '.github/**/*.yml'

packages-requirements:
  - 'requirements.txt'

packages-setup:
  - 'setup.py'

source:
  - 'src/**/*.py'

test:
  - 'test/*.py'

src:
  - 'src/*.py'
